# Generated by Django 3.2.5 on 2021-07-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20210702_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arzt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vorname', models.CharField(max_length=255, null=True)),
                ('nachname', models.CharField(max_length=255, null=True)),
                ('praxisname', models.CharField(max_length=255, null=True)),
                ('strasse', models.CharField(max_length=255, null=True)),
                ('nr', models.CharField(max_length=10, null=True)),
                ('plz', models.CharField(max_length=10, null=True)),
                ('ort', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medikament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medikamentenname', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medikamentenplan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vorname', models.CharField(max_length=255, null=True)),
                ('nachname', models.CharField(max_length=255, null=True)),
                ('strasse', models.CharField(max_length=255, null=True)),
                ('nr', models.CharField(max_length=10, null=True)),
                ('plz', models.CharField(max_length=10, null=True)),
                ('ort', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle_bezeichnung', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medikamentenplan_Medikamente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wochentag', models.CharField(max_length=50, null=True)),
                ('uhrzeit', models.CharField(max_length=50, null=True)),
                ('menge', models.CharField(max_length=50, null=True)),
                ('kommentar', models.CharField(max_length=50, null=True)),
                ('medikament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.medikament')),
                ('medikamentenplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.medikamentenplan')),
            ],
        ),
        migrations.AddField(
            model_name='medikamentenplan',
            name='medikamente',
            field=models.ManyToManyField(through='rest.Medikamentenplan_Medikamente', to='rest.Medikament'),
        ),
        migrations.AddField(
            model_name='medikamentenplan',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.patient'),
        ),
        migrations.AlterField(
            model_name='medikamentenbestellung',
            name='medikamentenname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.medikament'),
        ),
    ]
