# Generated by Django 3.2.5 on 2021-07-07 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20210706_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='medikamentenbestellung',
            name='arzt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.arzt'),
        ),
        migrations.AddField(
            model_name='medikamentenbestellung',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.patient'),
        ),
        migrations.AddField(
            model_name='medikamentenbestellung',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medikamentenplan',
            name='medikamente',
            field=models.ManyToManyField(null=True, through='rest.Medikamentenplan_Medikamente', to='rest.Medikament'),
        ),
    ]
