# Generated by Django 3.2.5 on 2021-07-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20210707_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Krankenkasse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
