# Generated by Django 3.2.5 on 2021-07-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_krankenkasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
