# Generated by Django 3.2.5 on 2021-07-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20210714_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='arzt',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='arzt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.arzt'),
        ),
    ]
