# Generated by Django 3.2.5 on 2021-07-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20210714_1738'),
        ('rest', '0007_medikamentenbestellung_dosis'),
    ]

    operations = [
    ]
