# Generated by Django 3.2.5 on 2021-07-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20210715_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='medikamentenbestellung',
            name='liefertermin',
            field=models.DateField(null=True),
        ),
    ]
