# Generated by Django 3.2.5 on 2021-07-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_merge_20210715_2207'),
        ('rest', '0010_medikamentenbestellung_liefertermin'),
    ]

    operations = [
    ]
